version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres-db
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    env_file:
      - .env
    ports:
      - '5432:5432'
    image: postgres:latest
    restart: always
    networks:
      - app
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: npm run start:dev
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - '4000:4000'
    image: home-library:latest
    restart: always
    depends_on:
      - db
    networks:
      - app
volumes:
  db_data:
    name: db_data
    driver: local
  db_logs:
    name: db_logs
    driver: local
networks:
  db:
  app:
    driver: bridge
